### ISSUE TITLE
New options for browse.yml

### ISSUE THREAD

**Issue by goflishMC** [magemonkeystudio/fusion#33]
```
professions:
  tinker:
    cost:
      #Currency cost to unlock
      money: 500
      #Minecraft experience cost to unlock
      experience: 400
    conditions:
      #Requirements need to be met in order
      #to unlock. <fusionProfession>: <level requirement>
      professions:
        blacksmith: 50
        leatherwork: 25
      #Requirements need to be met in order
      #to unlock. <FabledClass>: <level requirement>
      fabled:
        crafter: 25
        warrior: 50
```

**Comment by MaksyKun** [comment]
My additional wishes: Having conditions from external plugins like mcMMO and JobsReborn

```
conditions:
      #Requirements need to be met in order
      #to unlock. <fusionProfession>: <level requirement>
      professions:
        blacksmith: 50
        leatherwork: 25
      #Requirements need to be met in order
      #to unlock. <FabledClass>: <level requirement>
      fabled:
        crafter: 25
        warrior: 50
      mcmmo:
        alchemy: 250
        repair: 100
      jobs:
        alchemist: 20
```
