### ISSUE TITLE
[Enhancement] New permissions

### ISSUE THREAD

**Issue by materialplane** [magemonkeystudio/fusion#47]
Add `fusion.experience.<profession>.boost.<percentage>.<seconds>`

example: to get 10% increase in all professions experience `fusion.experience.global.boost.110.300`
This would give 10% increase in all profession experience for 5 minutes

`fusion.experience.smelting.boost.110.300`
This would only give 10% increase in the smelting profession

**Comment by MaksyKun** [comment]
I see the point in giving boosters to players, but in my opinion it would become pretty nested and tricky to handle those seconds to be cut out in the permission etc.

My suggestion to achieve boosters would be the following:
There will be a config-folder `boosters` which allows for infinite booster creations. We directly start to make them sub-folder compatible to avoid the request in future.

Via Database (SQLite or MySQL), players will get their booster. This can be achieve with an admin command like `craft booster give [player] [booster] [amount]` or something similar. Then, using `/craft booster` allows the player use their boosters.

My first idea of how such a booster file could look like:
```yaml
professions:
  armor_smithing:
    exp: 0.1 # provide 10% exp bonus for armor smithing
  weapon_smithing:
    exp: 0.25 # provide 25% exp bonus for weapon smithing

duration: 300 # The boost works for 5 minutes (300 seconds)
activateInstant: true # In case you want to make this booster instantly activate without player interaction, this will enable it automatically
```
