### ISSUE TITLE
[Enhancement] Hide Option for Profession Level

### ISSUE THREAD

**Issue by MaksyKun** [magemonkeystudio/fusion#54]
Add an option to hide recipes when players dont have the right profession level

**Comment by materialplane** [comment]
It would be nice to be able to show a placeholder icon if the recipe can't be crafted.

**Comment by MaksyKun** [comment]
I'd probably change the global section from:
```yml
hideRecipesDefault:
  noPermission: true
  noRank: false
  recipeLimitReached: false
```

to something like:
```yml
hidingDefaults:
  options:
    noPermission: true
    recipeLimitReached: true
    insufficientLevel: true
  placeholder:
    enabled: true
    icon:
      material: [-]
      name: [-]
   [...]
  excludedRecipes:
  - recipe1
  - recipe2
  - [...]
```

The last section is meant to be used for a "You will see when its time"-feeling for extra specific recipes. Im sure this might be needed someday
